### ISSUE TITLE
Add RetryPolicy

### ISSUE THREAD

**Issue by black-byte** [joseftw/jos.httpclient#1]
Hi,
In the article you have mentioned something about retry policy using Polly.
https://josefottosson.se/you-are-probably-still-using-httpclient-wrong-and-it-is-destabilizing-your-software/

Do you plan to share maybe some implementation of yours on that ? :)

**Comment by joseftw** [comment]
Sorry, haven't seen this issue for some reason.

Yes! Im working on a post regarding Error handling! :)

**Comment by black-byte** [comment]
Thanks for reply 👍 Do you have any ETA on this ?
