### ISSUE TITLE
IGitHubClient not necessary?

### ISSUE THREAD

**Issue by petermorlion** [joseftw/jos.httpclient#16]
I see you introduced an IGitHubClient, but apart from implementing it, it is never used. Wouldn't it be better to inject (or return from the factory) the interface instead of the actual type? Or else remove the interface? Or is there a reason you do it the way you do?

**Comment by joseftw** [comment]
It only exists to ensure that the different "versions" keep the same contract. In a production environment it would not be neccessary :)
