### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by davecameos** [joseftw/jos.httpclient#3]
Hi

This repo looks very good. Thank you.

Where can I find the instructions to run the benchmark or specific versions? 

Thanks

**Comment by joseftw** [comment]
Hello!

I've not published any instructions, will add it to the README asap.

Anyhow, it's quite easy.

1. Clone the repository
2. ```cd jos.httpclient```
3. ```dotnet build -c Release```
4. ```dotnet run src/JOS.HttpClient.GitHubDummyApi -c Release```
5. ```cd /src/JOS.HttpClient.Benchmark/bin/Release/netcore```
6. ```dotnet JOS.HttpClient.Benchmark.dll```

You can control how many items the Dummy API should return by changing this parameter:
https://github.com/joseftw/jos.httpclient/blob/develop/src/JOS.HttpClient.GitHubDummyApi/GitHubRepositoriesProvider.cs#L29
